version: '3'
services:
  mysql:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: jasonhonghh
      MYSQL_DATABASE: gochat
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  # kafka:
  #   image: wurstmeister/kafka:latest
  #   ports:
  #     - "9092:9092"
  #   environment:
  #     KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
  #     KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
  #     KAFKA_BROKER_ID: 1
  #     KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
  #   volumes:
  #     - /var/run/docker.sock:/var/run/docker.sock

  # apache:
  #   image: httpd:latest
  #   ports:
  #     - "80:80"
  #   volumes:
  #     - ./public-html:/usr/local/apache2/htdocs/

  # coturn:
  #   image: coturn/coturn:latest
  #   ports:
  #     - "3478:3478"
  #     - "5349:5349"
  #   volumes:
  #     - coturn_data:/etc/coturn

volumes:
  mysql_data:
  redis_data:
  coturn_data: